replicaCount: 1

image:
  repository: ghcr.io/coinwing/msa-broadcaster
  tag: latest
  pullPolicy: Always
  pullSecretName: ghcr-login-secret

containerPort: 8083

service:
  type: ClusterIP
  port: 80
